name: Staging deployment

on: 
  pull_request:
        types: [labeled]
env:
  DOCKER_IMAGE_NAME: sk9749992-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: sk9749992-ttt-app
  #################################################
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
           # Artifact name
          name: webpack artifacts
           # A file, directory or wildcard pattern that describes what to upload
          path: public/
          
  Build-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.3.4
        
      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: public
          
      - name: create image and store in package
        uses: mattdavis0351/actions/docker-gpr@1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          image-name: ${{env.DOCKER_IMAGE_NAME}}
          
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
           # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{env.IMAGE_REGISTRY_URL}}
          # Username used to log against the Docker registry
          username: ${{ github.actor }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.DOCKER_IMAGE_NAME}}:${{ github.sha }}
      - name: Azure logout
        run: |
          az logout
          
      
  

          
      
